// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8974831255870065141),
      name: 'HomeDevice',
      lastPropertyId: const obx_int.IdUid(10, 4621237047098505837),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8105830637994087426),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7604676019870404873),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6750202413780191200),
            name: 'brand',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2248267615147477292),
            name: 'modelNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7032575398926269719),
            name: 'serialNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8378310830085380576),
            name: 'purchaseDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4000069306332462525),
            name: 'warrantyExpiry',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7297338021509203411),
            name: 'roomLocation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2447611004603285252),
            name: 'notes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4621237047098505837),
            name: 'imagePath',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3038155747572638665),
      name: 'MaintenanceRecord',
      lastPropertyId: const obx_int.IdUid(7, 958730561267547455),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3577596765149948439),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7496391093440504512),
            name: 'deviceId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 9111613576894686205),
            relationTarget: 'HomeDevice'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3637030732385688199),
            name: 'taskName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9112053840964915497),
            name: 'serviceDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8372298826960309363),
            name: 'technicianName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7675571136232466908),
            name: 'cost',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 958730561267547455),
            name: 'description',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 3038155747572638665),
      lastIndexId: const obx_int.IdUid(1, 9111613576894686205),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    HomeDevice: obx_int.EntityDefinition<HomeDevice>(
        model: _entities[0],
        toOneRelations: (HomeDevice object) => [],
        toManyRelations: (HomeDevice object) => {},
        getId: (HomeDevice object) => object.id,
        setId: (HomeDevice object, int id) {
          object.id = id;
        },
        objectToFB: (HomeDevice object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final brandOffset = fbb.writeString(object.brand);
          final modelNumberOffset = fbb.writeString(object.modelNumber);
          final serialNumberOffset = fbb.writeString(object.serialNumber);
          final roomLocationOffset = object.roomLocation == null
              ? null
              : fbb.writeString(object.roomLocation!);
          final notesOffset =
              object.notes == null ? null : fbb.writeString(object.notes!);
          final imagePathOffset = object.imagePath == null
              ? null
              : fbb.writeString(object.imagePath!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, brandOffset);
          fbb.addOffset(3, modelNumberOffset);
          fbb.addOffset(4, serialNumberOffset);
          fbb.addInt64(5, object.purchaseDate?.millisecondsSinceEpoch);
          fbb.addInt64(6, object.warrantyExpiry?.millisecondsSinceEpoch);
          fbb.addOffset(7, roomLocationOffset);
          fbb.addOffset(8, notesOffset);
          fbb.addOffset(9, imagePathOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final purchaseDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final warrantyExpiryValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final brandParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final modelNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final serialNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final purchaseDateParam = purchaseDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(purchaseDateValue);
          final warrantyExpiryParam = warrantyExpiryValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(warrantyExpiryValue);
          final roomLocationParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final notesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final imagePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final object = HomeDevice(
              name: nameParam,
              brand: brandParam,
              modelNumber: modelNumberParam,
              serialNumber: serialNumberParam,
              purchaseDate: purchaseDateParam,
              warrantyExpiry: warrantyExpiryParam,
              roomLocation: roomLocationParam,
              notes: notesParam,
              imagePath: imagePathParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    MaintenanceRecord: obx_int.EntityDefinition<MaintenanceRecord>(
        model: _entities[1],
        toOneRelations: (MaintenanceRecord object) => [object.device],
        toManyRelations: (MaintenanceRecord object) => {},
        getId: (MaintenanceRecord object) => object.id,
        setId: (MaintenanceRecord object, int id) {
          object.id = id;
        },
        objectToFB: (MaintenanceRecord object, fb.Builder fbb) {
          final taskNameOffset = fbb.writeString(object.taskName);
          final technicianNameOffset = object.technicianName == null
              ? null
              : fbb.writeString(object.technicianName!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.device.targetId);
          fbb.addOffset(2, taskNameOffset);
          fbb.addInt64(3, object.serviceDate.millisecondsSinceEpoch);
          fbb.addOffset(4, technicianNameOffset);
          fbb.addFloat64(5, object.cost);
          fbb.addOffset(6, descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final taskNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final serviceDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final technicianNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final costParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 14);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final object = MaintenanceRecord(
              taskName: taskNameParam,
              serviceDate: serviceDateParam,
              technicianName: technicianNameParam,
              cost: costParam,
              description: descriptionParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.device.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.device.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HomeDevice] entity fields to define ObjectBox queries.
class HomeDevice_ {
  /// see [HomeDevice.id]
  static final id =
      obx.QueryIntegerProperty<HomeDevice>(_entities[0].properties[0]);

  /// see [HomeDevice.name]
  static final name =
      obx.QueryStringProperty<HomeDevice>(_entities[0].properties[1]);

  /// see [HomeDevice.brand]
  static final brand =
      obx.QueryStringProperty<HomeDevice>(_entities[0].properties[2]);

  /// see [HomeDevice.modelNumber]
  static final modelNumber =
      obx.QueryStringProperty<HomeDevice>(_entities[0].properties[3]);

  /// see [HomeDevice.serialNumber]
  static final serialNumber =
      obx.QueryStringProperty<HomeDevice>(_entities[0].properties[4]);

  /// see [HomeDevice.purchaseDate]
  static final purchaseDate =
      obx.QueryDateProperty<HomeDevice>(_entities[0].properties[5]);

  /// see [HomeDevice.warrantyExpiry]
  static final warrantyExpiry =
      obx.QueryDateProperty<HomeDevice>(_entities[0].properties[6]);

  /// see [HomeDevice.roomLocation]
  static final roomLocation =
      obx.QueryStringProperty<HomeDevice>(_entities[0].properties[7]);

  /// see [HomeDevice.notes]
  static final notes =
      obx.QueryStringProperty<HomeDevice>(_entities[0].properties[8]);

  /// see [HomeDevice.imagePath]
  static final imagePath =
      obx.QueryStringProperty<HomeDevice>(_entities[0].properties[9]);
}

/// [MaintenanceRecord] entity fields to define ObjectBox queries.
class MaintenanceRecord_ {
  /// see [MaintenanceRecord.id]
  static final id =
      obx.QueryIntegerProperty<MaintenanceRecord>(_entities[1].properties[0]);

  /// see [MaintenanceRecord.device]
  static final device = obx.QueryRelationToOne<MaintenanceRecord, HomeDevice>(
      _entities[1].properties[1]);

  /// see [MaintenanceRecord.taskName]
  static final taskName =
      obx.QueryStringProperty<MaintenanceRecord>(_entities[1].properties[2]);

  /// see [MaintenanceRecord.serviceDate]
  static final serviceDate =
      obx.QueryDateProperty<MaintenanceRecord>(_entities[1].properties[3]);

  /// see [MaintenanceRecord.technicianName]
  static final technicianName =
      obx.QueryStringProperty<MaintenanceRecord>(_entities[1].properties[4]);

  /// see [MaintenanceRecord.cost]
  static final cost =
      obx.QueryDoubleProperty<MaintenanceRecord>(_entities[1].properties[5]);

  /// see [MaintenanceRecord.description]
  static final description =
      obx.QueryStringProperty<MaintenanceRecord>(_entities[1].properties[6]);
}
